#define SYSCALL_WAIT 0
#define SYSCALL_FORK 1
#define SYSCALL_EXIT 2
#define SYSCALL_OPEN 3
#define SYSCALL_CLOSE 4
#define SYSCALL_READ 5
#define SYSCALL_WRITE 6
#define SYSCALL_SEEK 7
#define SYSCALL_SBRK 8
#define SYSCALL_EXEC 9
#define SYSCALL_GETCWD 10
#define SYSCALL_CHDIR 11
#define SYSCALL_DUP 12
#define SYSCALL_DUP2 13

#define NB_SYSCALLS 14

